#define UNICODE
#define _UNICODE

#include <windows.h>
#include <wtsapi32.h>
#include <userenv.h>
#include <tlhelp32.h>
#include <sddl.h>
#include <rpc.h>
#include <aclapi.h>
#include <vector>
#include <mutex>
#include <string>

// Generated by MIDL from TrayService.idl
#include "TrayService_h.h"

#pragma comment(lib, "wtsapi32.lib")
#pragma comment(lib, "userenv.lib")
#pragma comment(lib, "rpcrt4.lib")
#pragma comment(lib, "advapi32.lib")

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
#define SVC_NAME            L"TrayService"
#define APP_EXE_NAME        L"TrayApp.exe"
#define ALPC_ENDPOINT       L"TrayServiceEndpoint"
#define PARENT_MUTEX_NAME   L"Local\\TrayServiceParentMutex"

// ---------------------------------------------------------------------------
// Globals
// ---------------------------------------------------------------------------
static SERVICE_STATUS_HANDLE g_hStatus  = nullptr;
static SERVICE_STATUS        g_svcStatus = {};
static HANDLE                g_hRpcThread = nullptr;
static std::mutex            g_procMutex;
static std::vector<HANDLE>   g_appHandles;   // handles to launched TrayApp processes
static bool                  g_running = true;

// ---------------------------------------------------------------------------
// Forward declarations
// ---------------------------------------------------------------------------
VOID WINAPI ServiceMain(DWORD argc, LPWSTR* argv);
VOID WINAPI ServiceCtrlHandler(DWORD ctrl);
void        RunRpcServer();
void        LaunchAppInSession(DWORD sessionId);
void        LaunchAppInAllSessions();
void        MonitorSessions();
void        TerminateAllApps();
std::wstring GetServiceExeDir();

// ---------------------------------------------------------------------------
// Helpers – locate TrayApp.exe next to the service executable
// ---------------------------------------------------------------------------
std::wstring GetServiceExeDir()
{
    wchar_t path[MAX_PATH] = {};
    GetModuleFileName(nullptr, path, MAX_PATH);
    std::wstring dir(path);
    auto pos = dir.rfind(L'\\');
    if (pos != std::wstring::npos)
        dir.resize(pos + 1);
    return dir;
}

// ---------------------------------------------------------------------------
// Set service status helper
// ---------------------------------------------------------------------------
static void SetStatus(DWORD state, DWORD exitCode = NO_ERROR, DWORD waitHint = 0)
{
    g_svcStatus.dwCurrentState  = state;
    g_svcStatus.dwWin32ExitCode = exitCode;
    g_svcStatus.dwWaitHint      = waitHint;
    SetServiceStatus(g_hStatus, &g_svcStatus);
}

// ---------------------------------------------------------------------------
// Launch TrayApp.exe in a specific terminal session as that session's user
// ---------------------------------------------------------------------------
void LaunchAppInSession(DWORD sessionId)
{
    HANDLE hToken = nullptr;
    if (!WTSQueryUserToken(sessionId, &hToken))
        return;

    // Duplicate to a primary token suitable for CreateProcessAsUser
    HANDLE hPrimary = nullptr;
    if (!DuplicateTokenEx(hToken, MAXIMUM_ALLOWED, nullptr,
                          SecurityImpersonation, TokenPrimary, &hPrimary))
    {
        CloseHandle(hToken);
        return;
    }
    CloseHandle(hToken);

    // Load the user's environment block
    LPVOID pEnv = nullptr;
    CreateEnvironmentBlock(&pEnv, hPrimary, FALSE);

    // Build command line: TrayApp.exe --hidden
    std::wstring exePath = GetServiceExeDir() + APP_EXE_NAME;
    std::wstring cmdLine = L"\"" + exePath + L"\" --hidden";

    STARTUPINFO si         = {};
    PROCESS_INFORMATION pi = {};
    si.cb                  = sizeof(si);
    si.lpDesktop           = const_cast<LPWSTR>(L"winsta0\\default");
    si.dwFlags             = STARTF_USESHOWWINDOW;
    si.wShowWindow         = SW_HIDE;

    DWORD flags = CREATE_UNICODE_ENVIRONMENT | CREATE_NEW_CONSOLE;

    wchar_t cmdBuf[MAX_PATH * 2];
    wcsncpy_s(cmdBuf, cmdLine.c_str(), _TRUNCATE);

    if (CreateProcessAsUser(hPrimary, nullptr, cmdBuf,
                            nullptr, nullptr, FALSE,
                            flags, pEnv,
                            nullptr, &si, &pi))
    {
        std::lock_guard<std::mutex> lock(g_procMutex);
        g_appHandles.push_back(pi.hProcess);
        CloseHandle(pi.hThread);
    }

    if (pEnv) DestroyEnvironmentBlock(pEnv);
    CloseHandle(hPrimary);
}

// ---------------------------------------------------------------------------
// Launch TrayApp in all active terminal sessions (except session 0)
// ---------------------------------------------------------------------------
void LaunchAppInAllSessions()
{
    WTS_SESSION_INFO* pSessions = nullptr;
    DWORD count = 0;
    if (!WTSEnumerateSessions(WTS_CURRENT_SERVER_HANDLE, 0, 1, &pSessions, &count))
        return;

    for (DWORD i = 0; i < count; ++i)
    {
        if (pSessions[i].SessionId == 0)
            continue;
        if (pSessions[i].State == WTSActive || pSessions[i].State == WTSConnected)
            LaunchAppInSession(pSessions[i].SessionId);
    }
    WTSFreeMemory(pSessions);
}

// ---------------------------------------------------------------------------
// Monitor WTS session change events (new logins → launch app)
// ---------------------------------------------------------------------------
void MonitorSessions()
{
    // Register for WTS notifications on a hidden window
    WNDCLASS wc    = {};
    wc.lpfnWndProc = [](HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam) -> LRESULT
    {
        if (uMsg == WM_WTSSESSION_CHANGE)
        {
            if (wParam == WTS_SESSION_LOGON || wParam == WTS_REMOTE_CONNECT)
            {
                DWORD sessionId = static_cast<DWORD>(lParam);
                if (sessionId != 0)
                    LaunchAppInSession(sessionId);
            }
        }
        return DefWindowProc(hWnd, uMsg, wParam, lParam);
    };
    wc.hInstance     = GetModuleHandle(nullptr);
    wc.lpszClassName = L"TrayServiceWnd";
    RegisterClass(&wc);

    HWND hWnd = CreateWindow(L"TrayServiceWnd", L"", 0,
                             0, 0, 0, 0, HWND_MESSAGE,
                             nullptr, GetModuleHandle(nullptr), nullptr);
    if (!hWnd) return;

    WTSRegisterSessionNotification(hWnd, NOTIFY_FOR_ALL_SESSIONS);

    MSG msg;
    while (g_running && GetMessage(&msg, nullptr, 0, 0))
    {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }

    WTSUnRegisterSessionNotification(hWnd);
    DestroyWindow(hWnd);
}

// ---------------------------------------------------------------------------
// Terminate all launched TrayApp processes
// ---------------------------------------------------------------------------
void TerminateAllApps()
{
    std::lock_guard<std::mutex> lock(g_procMutex);
    for (HANDLE h : g_appHandles)
    {
        TerminateProcess(h, 0);
        CloseHandle(h);
    }
    g_appHandles.clear();
}

// ---------------------------------------------------------------------------
// RPC server thread
// ---------------------------------------------------------------------------
void RunRpcServer()
{
    RPC_STATUS status;

    status = RpcServerUseProtseqEp(
        reinterpret_cast<RPC_WSTR>(const_cast<wchar_t*>(L"ncalrpc")),
        RPC_C_PROTSEQ_MAX_REQS_DEFAULT,
        reinterpret_cast<RPC_WSTR>(const_cast<wchar_t*>(ALPC_ENDPOINT)),
        nullptr);
    if (status != RPC_S_OK) return;

    status = RpcServerRegisterIf2(
        ITrayService_v1_0_s_ifspec,
        nullptr, nullptr,
        RPC_IF_ALLOW_LOCAL_ONLY,
        RPC_C_LISTEN_MAX_CALLS_DEFAULT,
        static_cast<UINT>(-1),
        nullptr);
    if (status != RPC_S_OK) return;

    // Blocks until RpcMgmtStopServerListening is called
    RpcServerListen(1, RPC_C_LISTEN_MAX_CALLS_DEFAULT, FALSE);
}

// ---------------------------------------------------------------------------
// Optional req 2: Restrict the service process DACL so non-admins cannot
// open it with PROCESS_TERMINATE / PROCESS_VM_WRITE etc.
// WORLD gets PROCESS_QUERY_LIMITED_INFORMATION only; Admins/SYSTEM get full.
// ---------------------------------------------------------------------------
static void HardenServiceProcessDacl()
{
    HANDLE hProcess = GetCurrentProcess();
    const wchar_t* sddl =
        L"D:(A;;0x1000;;;WD)(A;;FA;;;BA)(A;;FA;;;SY)";

    PSECURITY_DESCRIPTOR pSD = nullptr;
    if (!ConvertStringSecurityDescriptorToSecurityDescriptor(
            sddl, SDDL_REVISION_1, &pSD, nullptr))
        return;

    PACL pDacl = nullptr;
    BOOL daclPresent = FALSE, daclDefaulted = FALSE;
    if (GetSecurityDescriptorDacl(pSD, &daclPresent, &pDacl, &daclDefaulted)
        && daclPresent)
    {
        SetSecurityInfo(hProcess, SE_KERNEL_OBJECT,
                        DACL_SECURITY_INFORMATION,
                        nullptr, nullptr, pDacl, nullptr);
    }
    LocalFree(pSD);
}

// ---------------------------------------------------------------------------
// Optional req 1: Show Yes/No confirmation via WTSSendMessage in the active
// terminal session before allowing service stop.
// Returns true if confirmed (or UI unavailable).
// ---------------------------------------------------------------------------
static bool ConfirmStopOnSecureDesktop()
{
    DWORD activeSession = WTSGetActiveConsoleSessionId();
    DWORD response   = 0;
    DWORD timeoutSec = 30;

    wchar_t title[]   = L"TrayService – Остановка";
    wchar_t message[] = L"\u0421\u043b\u0443\u0436\u0431\u0430 TrayService \u043f\u043e\u043b\u0443\u0447\u0438\u043b\u0430 \u0437\u0430\u043f\u0440\u043e\u0441 \u043d\u0430 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0443.\n"
                        L"\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0434\u0438\u0442\u0435 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0443 \u0441\u043b\u0443\u0436\u0431\u044b?";

    BOOL sent = WTSSendMessage(
        WTS_CURRENT_SERVER_HANDLE,
        activeSession,
        title,   static_cast<DWORD>((wcslen(title)   + 1) * sizeof(wchar_t)),
        message, static_cast<DWORD>((wcslen(message) + 1) * sizeof(wchar_t)),
        MB_YESNO | MB_ICONQUESTION | MB_DEFBUTTON2,
        timeoutSec,
        &response,
        TRUE);

    if (!sent) return true;
    return (response == IDYES);
}

// ---------------------------------------------------------------------------
// RPC interface implementation: StopService
// Client calls this to request service shutdown
// ---------------------------------------------------------------------------
void StopService(handle_t /*hBinding*/)
{
    // Optional req 1: ask for confirmation on the active session desktop
    if (!ConfirmStopOnSecureDesktop())
        return;  // user declined

    g_running = false;
    TerminateAllApps();
    SetStatus(SERVICE_STOP_PENDING, NO_ERROR, 3000);
    RpcMgmtStopServerListening(nullptr);
    SetStatus(SERVICE_STOPPED);
}

// ---------------------------------------------------------------------------
// RPC memory allocation (required by MIDL runtime)
// ---------------------------------------------------------------------------
void* __RPC_USER MIDL_user_allocate(size_t size) { return malloc(size); }
void  __RPC_USER MIDL_user_free(void* p)          { free(p); }

// ---------------------------------------------------------------------------
// Service control handler – Stop and Shutdown are intentionally ignored
// ---------------------------------------------------------------------------
VOID WINAPI ServiceCtrlHandler(DWORD ctrl)
{
    switch (ctrl)
    {
    case SERVICE_CONTROL_STOP:
    case SERVICE_CONTROL_SHUTDOWN:
        // Requirement 3: ignore Stop and Shutdown signals
        // The service can only be stopped via the RPC interface
        break;
    case SERVICE_CONTROL_INTERROGATE:
        SetServiceStatus(g_hStatus, &g_svcStatus);
        break;
    }
}

// ---------------------------------------------------------------------------
// ServiceMain
// ---------------------------------------------------------------------------
VOID WINAPI ServiceMain(DWORD /*argc*/, LPWSTR* /*argv*/)
{
    g_hStatus = RegisterServiceCtrlHandler(SVC_NAME, ServiceCtrlHandler);
    if (!g_hStatus) return;

    g_svcStatus.dwServiceType             = SERVICE_WIN32_OWN_PROCESS;
    g_svcStatus.dwControlsAccepted        = 0; // accept nothing (stop/shutdown ignored)
    g_svcStatus.dwCurrentState            = SERVICE_START_PENDING;
    g_svcStatus.dwWin32ExitCode           = NO_ERROR;
    g_svcStatus.dwCheckPoint              = 0;
    g_svcStatus.dwWaitHint                = 3000;
    SetServiceStatus(g_hStatus, &g_svcStatus);

    // Launch app in all existing sessions
    LaunchAppInAllSessions();

    // Start session-monitor thread
    HANDLE hMonitor = CreateThread(nullptr, 0,
        [](LPVOID) -> DWORD { MonitorSessions(); return 0; },
        nullptr, 0, nullptr);

    // Optional req 2: harden process DACL (non-admins cannot terminate)
    HardenServiceProcessDacl();

    // Report running
    SetStatus(SERVICE_RUNNING);

    // Start RPC server (blocks until StopService() is called via RPC)
    RunRpcServer();

    // Cleanup
    g_running = false;
    PostThreadMessage(GetThreadId(hMonitor), WM_QUIT, 0, 0);
    WaitForSingleObject(hMonitor, 3000);
    CloseHandle(hMonitor);

    TerminateAllApps();
    SetStatus(SERVICE_STOPPED);
}

// ---------------------------------------------------------------------------
// main / WinMain
// ---------------------------------------------------------------------------
int wmain()
{
    SERVICE_TABLE_ENTRY dispatchTable[] =
    {
        { const_cast<LPWSTR>(SVC_NAME), ServiceMain },
        { nullptr, nullptr }
    };

    StartServiceCtrlDispatcher(dispatchTable);
    return 0;
}
